import cameron from "./assets/cameron.png";
import devon from "./assets/devon.png";
import esther from "./assets/esther.png";
import floyd from "./assets/floyd.png";
import jane from "./assets/jane.png";
import marvin from "./assets/marvin.png";
import arlene from "./assets/arlene.png";
import ronald from "./assets/ronald.png";
import jessica from "./assets/jessica.png";
import will from "./assets/will.png";

import folderIcon from "./assets/folderIcon.png";
import pngIcon from "./assets/pngIcon.png";
import pdfIcon from "./assets/pdfIcon.png";
import docIcon from "./assets/docIcon.png";

// TYPES
export type employeeOverviewType = {
  name: string;
  img: string;
  jobTitle: string;
  department: string;
  email: string;
  status: string;
  statusColor: string;
  numberOfKPIs: number;
  KPIScore: number;
  monthlyAvg: number;
  totalSalary: number;
  grossSalary: number;
  taxes: number;
  netSalary: number;
  salaryStatus: string;
  salaryStatusColor: string;
};

export type chartDataType = {
  name: string;
  RetentionRate: number;
  TurnoverRate: number;
};

export type pieChartData = {
  name: string;
  value: number;
};

export type keyIndicatorDataType = {
  month: string;
  val1: number;
  val2: number;
  val3: number;
};

export type documentType = {
  thumbnail: string;
  typeOfDoc: string;
  name: string;
  size: string;
  date: string;
  filterType: string;
};

// CONST

export const employeeOverview: { [key: string]: employeeOverviewType } = {
  willJohn: {
    name: "will john",
    img: will,
    jobTitle: "product designer",
    department: "product",
    email: "willjohn@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 8,
    KPIScore: 70,
    monthlyAvg: 72,
    totalSalary: 100000,
    grossSalary: 5000,
    taxes: 370.23,
    netSalary: 5000 - 370.23,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  jessicaReel: {
    name: "jessica reel",
    img: jessica,
    jobTitle: "product manager",
    department: "product",
    email: "jessicaforeel@gmail.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 8,
    KPIScore: 52,
    monthlyAvg: 55,
    totalSalary: 120000,
    grossSalary: 7200,
    taxes: 570.13,
    netSalary: 7200 - 570.13,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  ronaldRichard: {
    name: "ronald richard",
    img: ronald,
    jobTitle: "front-end engineer",
    department: "engineering",
    email: "ronrich@yahoo.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 14,
    KPIScore: 74,
    monthlyAvg: 78,
    totalSalary: 90000,
    grossSalary: 4100,
    taxes: 290.93,
    netSalary: 4100 - 290.93,
    salaryStatus: "pending",
    salaryStatusColor: "text-[#EF5F04]",
  },
  estherHoward: {
    name: "esther howard",
    img: esther,
    jobTitle: "back-end engineer",
    department: "engineering",
    email: "estward@gmail.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 14,
    KPIScore: 72,
    monthlyAvg: 75,
    totalSalary: 110000,
    grossSalary: 5500,
    taxes: 400.93,
    netSalary: 5500 - 400.93,
    salaryStatus: "not paid",
    salaryStatusColor: "text-[#EF5F04]",
  },
  arleneMccoy: {
    name: "arlene mccoy",
    img: arlene,
    jobTitle: "fullstack engineer",
    department: "engineering",
    email: "mcarlene@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 1,
    KPIScore: 20,
    monthlyAvg: 21,
    totalSalary: 115000,
    grossSalary: 5250,
    taxes: 400.67,
    netSalary: 5259 - 400.67,
    salaryStatus: "pending",
    salaryStatusColor: "text-[#047E04]",
  },
  floydMiles: {
    name: "floyd miles",
    img: floyd,
    jobTitle: "fullstack engineer",
    department: "engineering",
    email: "floydmi@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 9,
    KPIScore: 59,
    monthlyAvg: 66,
    totalSalary: 130000,
    grossSalary: 7150,
    taxes: 573.72,
    netSalary: 7150 - 573.72,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  janeCooper: {
    name: "jane cooper",
    img: jane,
    jobTitle: "product manager",
    department: "product",
    email: "jacoop@outlook.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 4,
    KPIScore: 66,
    monthlyAvg: 69,
    totalSalary: 100000,
    grossSalary: 5200,
    taxes: 347.67,
    netSalary: 5200 - 347.67,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  marvinMckinney: {
    name: "marvin mcckinney",
    img: marvin,
    jobTitle: "front-end engineer",
    department: "engineering",
    email: "willjohn@gmail.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 10,
    KPIScore: 40,
    monthlyAvg: 45,
    totalSalary: 95000,
    grossSalary: 4500,
    taxes: 299.08,
    netSalary: 4500 - 299.08,
    salaryStatus: "not paid",
    salaryStatusColor: "text-[#EF5F04]",
  },
  cameronWilliamson: {
    name: "cameron williamson",
    img: cameron,
    jobTitle: "HR",
    department: "human resources",
    email: "cameronwilliamson@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 9,
    KPIScore: 57,
    monthlyAvg: 61,
    totalSalary: 105000,
    grossSalary: 5750,
    taxes: 675.58,
    netSalary: 5750 - 675.58,
    salaryStatus: "pending",
    salaryStatusColor: "text-[#EF5F04]",
  },
  devonLane: {
    name: "devon lane",
    img: devon,
    jobTitle: "devOps engineer",
    department: "engineering",
    email: "devonLane@yahoo.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 11,
    KPIScore: 60,
    monthlyAvg: 65,
    totalSalary: 135000,
    grossSalary: 7900,
    taxes: 611.18,
    netSalary: 7900 - 611.18,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  averyJackson: {
    name: "avery jackson",
    img: cameron,
    jobTitle: "product designer",
    department: "product",
    email: "averyjackson@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 8,
    KPIScore: 70,
    monthlyAvg: 68,
    totalSalary: 115000,
    grossSalary: 9600,
    taxes: 700.5,
    netSalary: 9600 - 700.5,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  taylorMoore: {
    name: "taylor moore",
    img: arlene,
    jobTitle: "back-end engineer",
    department: "engineering",
    email: "taylormoore@yahoo.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 10,
    KPIScore: 50,
    monthlyAvg: 55,
    totalSalary: 98000,
    grossSalary: 8200,
    taxes: 650.25,
    netSalary: 8200 - 650.25,
    salaryStatus: "not paid",
    salaryStatusColor: "text-[#EF5F04]",
  },
  jordanSmith: {
    name: "jordan smith",
    img: marvin,
    jobTitle: "HR",
    department: "human resources",
    email: "jordansmith@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 12,
    KPIScore: 65,
    monthlyAvg: 60,
    totalSalary: 90000,
    grossSalary: 7500,
    taxes: 500.1,
    netSalary: 7500 - 500.1,
    salaryStatus: "pending",
    salaryStatusColor: "text-[#EF5F04]",
  },
  caseyLee: {
    name: "casey lee",
    img: esther,
    jobTitle: "fullstack engineer",
    department: "engineering",
    email: "caseylee@yahoo.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 9,
    KPIScore: 58,
    monthlyAvg: 62,
    totalSalary: 122000,
    grossSalary: 10100,
    taxes: 755.65,
    netSalary: 10100 - 755.65,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  alexReed: {
    name: "alex reed",
    img: cameron,
    jobTitle: "devOps engineer",
    department: "engineering",
    email: "alexreed@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 11,
    KPIScore: 72,
    monthlyAvg: 70,
    totalSalary: 140000,
    grossSalary: 11600,
    taxes: 900.3,
    netSalary: 11600 - 900.3,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  rileyBrown: {
    name: "riley brown",
    img: jane,
    jobTitle: "front-end engineer",
    department: "engineering",
    email: "rileybrown@gmail.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 10,
    KPIScore: 55,
    monthlyAvg: 50,
    totalSalary: 100000,
    grossSalary: 8300,
    taxes: 589.75,
    netSalary: 8300 - 589.75,
    salaryStatus: "not paid",
    salaryStatusColor: "text-[#EF5F04]",
  },
  quinnPatel: {
    name: "quinn patel",
    img: ronald,
    jobTitle: "devOps engineer",
    department: "engineering",
    email: "quinnpatel@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 10,
    KPIScore: 67,
    monthlyAvg: 72,
    totalSalary: 150000,
    grossSalary: 12500,
    taxes: 950.5,
    netSalary: 12500 - 950.5,
    salaryStatus: "paid",
    salaryStatusColor: "text-[#047E04]",
  },
  morganCarter: {
    name: "morgan carter",
    img: devon,
    jobTitle: "back-end engineer",
    department: "engineering",
    email: "morgancarter@gmail.com",
    status: "remote",
    statusColor: "text-[#EF5F04]",
    numberOfKPIs: 11,
    KPIScore: 62,
    monthlyAvg: 65,
    totalSalary: 130000,
    grossSalary: 10800,
    taxes: 800.45,
    netSalary: 10800 - 800.45,
    salaryStatus: "not paid",
    salaryStatusColor: "text-[#EF5F04]",
  },
  kellyMurphy: {
    name: "kelly murphy",
    img: jessica,
    jobTitle: "HR",
    department: "human resources",
    email: "kellymurphy@gmail.com",
    status: "on site",
    statusColor: "text-[#047E04]",
    numberOfKPIs: 10,
    KPIScore: 59,
    monthlyAvg: 58,
    totalSalary: 95000,
    grossSalary: 7900,
    taxes: 600.25,
    netSalary: 7900 - 600.25,
    salaryStatus: "pending",
    salaryStatusColor: "text-[#EF5F04]",
  },
};

export const chartData: chartDataType[] = [
  {
    name: "2020",
    RetentionRate: 75,
    TurnoverRate: 20,
  },
  {
    name: "2021",
    RetentionRate: 45,
    TurnoverRate: 55,
  },
  {
    name: "2022",
    RetentionRate: 35,
    TurnoverRate: 65,
  },
  {
    name: "2023",
    RetentionRate: 40,
    TurnoverRate: 60,
  },
  {
    name: "2024",
    RetentionRate: 20,
    TurnoverRate: 80,
  },
];

export const data: pieChartData[] = [
  { name: "contractStaff", value: 127 },
  { name: "fulltimeStaff", value: 273 },
];

export const efficiencyData: pieChartData[] = [
  { name: "efficient", value: 80 },
  { name: "notEfficient", value: 20 },
];

export const keyIndicator: keyIndicatorDataType[] = [
  {
    month: "Jan",
    val1: 100,
    val2: 75,
    val3: 25,
  },
  {
    month: "Feb",
    val1: 85,
    val2: 66,
    val3: 72,
  },
  {
    month: "Mar",
    val1: 95,
    val2: 53,
    val3: 44,
  },
  {
    month: "Apr",
    val1: 29,
    val2: 63,
    val3: 95,
  },
  {
    month: "May",
    val1: 60,
    val2: 96,
    val3: 28,
  },
  {
    month: "Jun",
    val1: 84,
    val2: 39,
    val3: 49,
  },
];

export const folders: documentType[] = [
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Public documents",
    size: "2 GB",
    date: "12-01-24",
    filterType: "updated",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Appraisal forms",
    size: "10.2 MB",
    date: "07-01-24",
    filterType: "updated",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Satisfaction surveys",
    size: "4 GB",
    date: "01-02-24",
    filterType: "shared",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "admin reports",
    size: "1 GB",
    date: "21-02-24",
    filterType: "added",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "EPR",
    size: "3.1 GB",
    date: "11-02-24",
    filterType: "updated",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Project Plans",
    size: "500 MB",
    date: "14-03-24",
    filterType: "shared",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Financial Reports",
    size: "2.5 GB",
    date: "28-01-24",
    filterType: "added",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "HR Policies",
    size: "1.2 GB",
    date: "19-02-24",
    filterType: "added",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Training Materials",
    size: "750 MB",
    date: "05-03-24",
    filterType: "shared",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Marketing Assets",
    size: "3 GB",
    date: "22-02-24",
    filterType: "shared",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Sales Data",
    size: "1.5 GB",
    date: "18-01-24",
    filterType: "added",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Meeting Notes",
    size: "200 MB",
    date: "12-03-24",
    filterType: "added",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Technical Specifications",
    size: "850 MB",
    date: "25-01-24",
    filterType: "updated",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Annual Reviews",
    size: "2 GB",
    date: "30-01-24",
    filterType: "shared",
  },
  {
    thumbnail: folderIcon,
    typeOfDoc: "folder",
    name: "Legal Documents",
    size: "4.5 GB",
    date: "10-03-24",
    filterType: "added",
  },
];

export const files: documentType[] = [
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "game Plans",
    size: "2.2 MB",
    date: "17-03-24",
    filterType: "updated",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Project Plans",
    size: "25 MB",
    date: "11-03-24",
    filterType: "updated",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Project Plans",
    size: "27 kb",
    date: "04-04-24",
    filterType: "shared",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Team Meeting Notes",
    size: "1.5 MB",
    date: "05-03-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Annual Report",
    size: "12 MB",
    date: "10-02-24",
    filterType: "shared",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Company Logo",
    size: "50 KB",
    date: "21-01-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Financial Summary",
    size: "30 MB",
    date: "08-03-24",
    filterType: "added",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Employee Handbook",
    size: "4.5 MB",
    date: "15-02-24",
    filterType: "added",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Product Images",
    size: "300 KB",
    date: "01-02-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Marketing Strategy",
    size: "22 MB",
    date: "19-02-24",
    filterType: "updated",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Client Contracts",
    size: "7.8 MB",
    date: "07-03-24",
    filterType: "shared",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Sales Report Q1",
    size: "14 MB",
    date: "23-01-24",
    filterType: "shared",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Infographic",
    size: "120 KB",
    date: "14-02-24",
    filterType: "shared",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Project Proposal",
    size: "3.2 MB",
    date: "09-03-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Research Paper",
    size: "9 MB",
    date: "20-01-24",
    filterType: "added",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Event Poster",
    size: "85 KB",
    date: "12-02-24",
    filterType: "shared",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Budget Report",
    size: "15 MB",
    date: "03-03-24",
    filterType: "updated",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Training Manual",
    size: "5.6 MB",
    date: "28-01-24",
    filterType: "updated",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Product Screenshot",
    size: "110 KB",
    date: "17-02-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Workshop Materials",
    size: "20 MB",
    date: "13-03-24",
    filterType: "added",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Technical Documentation",
    size: "6.4 MB",
    date: "24-01-24",
    filterType: "shared",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Policy Document",
    size: "10 MB",
    date: "02-03-24",
    filterType: "shared",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Diagram",
    size: "70 KB",
    date: "11-02-24",
    filterType: "added",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Meeting Agenda",
    size: "2 MB",
    date: "05-02-24",
    filterType: "updated",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Audit Report",
    size: "18 MB",
    date: "22-01-24",
    filterType: "updated",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Chart",
    size: "90 KB",
    date: "27-02-24",
    filterType: "added",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Work Plan",
    size: "3 MB",
    date: "14-03-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Quarterly Review",
    size: "17 MB",
    date: "26-02-24",
    filterType: "updated",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Wireframe",
    size: "60 KB",
    date: "03-02-24",
    filterType: "shared",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Business Plan",
    size: "4 MB",
    date: "18-03-24",
    filterType: "added",
  },
  {
    thumbnail: pdfIcon,
    typeOfDoc: "pdf",
    name: "Compliance Report",
    size: "12 MB",
    date: "07-03-24",
    filterType: "updated",
  },
  {
    thumbnail: pngIcon,
    typeOfDoc: "png",
    name: "Flowchart",
    size: "95 KB",
    date: "09-02-24",
    filterType: "shared",
  },
  {
    thumbnail: docIcon,
    typeOfDoc: "doc",
    name: "Requirements Document",
    size: "5 MB",
    date: "20-03-24",
    filterType: "added",
  },
];
